version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: Set up pipenv.
          command: pip install pipenv
      - run:
          name: Install dependencies.
          command: pipenv install --dev
      - run:
          name: Install package
          command: pipenv install -e .
      - run:
          name: Run tests.
          command: pipenv run py.test --junitxml=pytest/results.xml --cov=gitsecret tests/unit
      - run:
          name: Lint code.
          command: pipenv run pylint gitsecret -f parseable >> pylint.log
      - run:
          name: Run mypy
          command: pipenv run mypy gitsecret >> mypy.log
      - store_test_results:
          path: pytest
      - store_artifacts:
          path: pylint.log
      - store_artifacts:
          path: mypy.log
      - run:
          name: Send code coverage to Coveralls
          command: pipenv run coveralls

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
